# Generated by Django 3.0.3 on 2020-02-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('url', models.TextField()),
                ('title', models.TextField(blank=True)),
                ('window_width', models.PositiveIntegerField()),
                ('window_height', models.PositiveIntegerField()),
                ('referer', models.TextField(blank=True)),
                ('unique_visit', models.BooleanField()),
            ],
        ),
    ]
