# Generated by Django 3.0.3 on 2020-02-23 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tid', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('url', models.TextField()),
                ('title', models.TextField(blank=True)),
                ('window_width', models.PositiveIntegerField()),
                ('window_height', models.PositiveIntegerField()),
                ('referer', models.TextField(blank=True)),
                ('unique_visit', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='core.Project')),
            ],
        ),
    ]
